INSERT INTO ref_pmu2 (id, name) VALUES (1, 'Кожа, подкожно - жировая клетчатка, придатки кожи');
INSERT INTO ref_pmu2 (id, name) VALUES (2, 'Мышечная система');
INSERT INTO ref_pmu2 (id, name) VALUES (3, 'Костная система');
INSERT INTO ref_pmu2 (id, name) VALUES (4, 'Суставы');
INSERT INTO ref_pmu2 (id, name) VALUES (5, 'Система органов кроветворения и кровь');
INSERT INTO ref_pmu2 (id, name) VALUES (6, 'Иммунная система');
INSERT INTO ref_pmu2 (id, name) VALUES (7, 'Полость рта и зубы');
INSERT INTO ref_pmu2 (id, name) VALUES (8, 'Верхние дыхательные пути');
INSERT INTO ref_pmu2 (id, name) VALUES (9, 'Нижние дыхательные пути и легочная ткань');
INSERT INTO ref_pmu2 (id, name) VALUES (10, 'Сердце и перикард');
INSERT INTO ref_pmu2 (id, name) VALUES (11, 'Медиастинум');
INSERT INTO ref_pmu2 (id, name) VALUES (12, 'Крупные кровеносные сосуды');
INSERT INTO ref_pmu2 (id, name) VALUES (13, 'Система микроциркуляции');
INSERT INTO ref_pmu2 (id, name) VALUES (14, 'Печень и желчевыводящие пути');
INSERT INTO ref_pmu2 (id, name) VALUES (15, 'Поджелудочная железа');
INSERT INTO ref_pmu2 (id, name) VALUES (16, 'Пищевод, желудок, 12-перстная кишка');
INSERT INTO ref_pmu2 (id, name) VALUES (17, 'Тонкий кишечник');
INSERT INTO ref_pmu2 (id, name) VALUES (18, 'Толстый кишечник');
INSERT INTO ref_pmu2 (id, name) VALUES (19, 'Сигмовидная и прямая кишка');
INSERT INTO ref_pmu2 (id, name) VALUES (20, 'Женские половые органы');
INSERT INTO ref_pmu2 (id, name) VALUES (21, 'Мужские половые органы');
INSERT INTO ref_pmu2 (id, name) VALUES (22, 'Железы внутренней секреции');
INSERT INTO ref_pmu2 (id, name) VALUES (23, 'Центральная нервная система и головной мозг');
INSERT INTO ref_pmu2 (id, name) VALUES (24, 'Периферическая нервная система');
INSERT INTO ref_pmu2 (id, name) VALUES (25, 'Орган слуха');
INSERT INTO ref_pmu2 (id, name) VALUES (26, 'Орган зрения');
INSERT INTO ref_pmu2 (id, name) VALUES (27, 'Орган обоняния');
INSERT INTO ref_pmu2 (id, name) VALUES (28, 'Почки и мочевыделительный тракт');
INSERT INTO ref_pmu2 (id, name) VALUES (30, 'Психическая сфера');
INSERT INTO ref_pmu2 (id, name) VALUES (31, 'Прочие');
