INSERT INTO ref_skmu2 (id, name) VALUES (1, 'Акушерство и гинекология');
INSERT INTO ref_skmu2 (id, name) VALUES (2, 'Аллергология и иммунология');
INSERT INTO ref_skmu2 (id, name) VALUES (3, 'Анестезиология и реаниматология');
INSERT INTO ref_skmu2 (id, name) VALUES (4, 'Гастроэнтерология');
INSERT INTO ref_skmu2 (id, name) VALUES (5, 'Гематология');
INSERT INTO ref_skmu2 (id, name) VALUES (6, 'Генетика');
INSERT INTO ref_skmu2 (id, name) VALUES (7, 'Гериатрия');
INSERT INTO ref_skmu2 (id, name) VALUES (8, 'Дерматовенерология');
INSERT INTO ref_skmu2 (id, name) VALUES (9, 'Детская онкология');
INSERT INTO ref_skmu2 (id, name) VALUES (10, 'Детская хирургия');
INSERT INTO ref_skmu2 (id, name) VALUES (13, 'Диетология');
INSERT INTO ref_skmu2 (id, name) VALUES (14, 'Инфекционные болезни');
INSERT INTO ref_skmu2 (id, name) VALUES (15, 'Кардиология');
INSERT INTO ref_skmu2 (id, name) VALUES (18, 'Колопроктология');
INSERT INTO ref_skmu2 (id, name) VALUES (20, 'Лечебная физкультура и спорт');
INSERT INTO ref_skmu2 (id, name) VALUES (23, 'Неврология');
INSERT INTO ref_skmu2 (id, name) VALUES (28, 'Оториноларингология');
INSERT INTO ref_skmu2 (id, name) VALUES (29, 'Офтальмология');
INSERT INTO ref_skmu2 (id, name) VALUES (31, 'Педиатрия');
INSERT INTO ref_skmu2 (id, name) VALUES (32, 'Неонатология');
INSERT INTO ref_skmu2 (id, name) VALUES (33, 'Профпатология');
INSERT INTO ref_skmu2 (id, name) VALUES (34, 'Психотерапия');
INSERT INTO ref_skmu2 (id, name) VALUES (35, 'Психиатрия');
INSERT INTO ref_skmu2 (id, name) VALUES (36, 'Психиатрия - наркология');
INSERT INTO ref_skmu2 (id, name) VALUES (37, 'Пульмонология');
INSERT INTO ref_skmu2 (id, name) VALUES (38, 'Радиология');
INSERT INTO ref_skmu2 (id, name) VALUES (39, 'Рентгенология');
INSERT INTO ref_skmu2 (id, name) VALUES (40, 'Ревматология');
INSERT INTO ref_skmu2 (id, name) VALUES (42, 'Сексология');
INSERT INTO ref_skmu2 (id, name) VALUES (44, 'Скорая медицинская помощь');
INSERT INTO ref_skmu2 (id, name) VALUES (45, 'Судебно - медицинская экспертиза');
INSERT INTO ref_skmu2 (id, name) VALUES (46, 'Сурдология - оториноларингология');
INSERT INTO ref_skmu2 (id, name) VALUES (47, 'Терапия');
INSERT INTO ref_skmu2 (id, name) VALUES (48, 'Токсикология');
INSERT INTO ref_skmu2 (id, name) VALUES (49, 'Торакальная хирургия');
INSERT INTO ref_skmu2 (id, name) VALUES (50, 'Травматология и ортопедия');
INSERT INTO ref_skmu2 (id, name) VALUES (53, 'Урология');
INSERT INTO ref_skmu2 (id, name) VALUES (54, 'Физиотерапия');
INSERT INTO ref_skmu2 (id, name) VALUES (55, 'Фтизиатрия');
INSERT INTO ref_skmu2 (id, name) VALUES (57, 'Хирургия');
INSERT INTO ref_skmu2 (id, name) VALUES (64, 'Стоматология детская');
INSERT INTO ref_skmu2 (id, name) VALUES (65, 'Стоматология терапевтическая');
INSERT INTO ref_skmu2 (id, name) VALUES (66, 'Стоматология ортопедическая');
INSERT INTO ref_skmu2 (id, name) VALUES (67, 'Стоматология хирургическая');
INSERT INTO ref_skmu2 (id, name) VALUES (68, 'Челюстно - лицевая хирургия');
INSERT INTO ref_skmu2 (id, name) VALUES (12, 'Диабетология');
INSERT INTO ref_skmu2 (id, name) VALUES (16, 'Клиническая лабораторная диагностика');
INSERT INTO ref_skmu2 (id, name) VALUES (24, 'Нейрохирургия');
INSERT INTO ref_skmu2 (id, name) VALUES (25, 'Нефрология');
INSERT INTO ref_skmu2 (id, name) VALUES (27, 'Онкология');
INSERT INTO ref_skmu2 (id, name) VALUES (43, 'Сердечно - сосудистая хирургия');
INSERT INTO ref_skmu2 (id, name) VALUES (51, 'Трансфузиология');
INSERT INTO ref_skmu2 (id, name) VALUES (52, 'Ультразвуковая диагностика');
INSERT INTO ref_skmu2 (id, name) VALUES (58, 'Эндокринология');
INSERT INTO ref_skmu2 (id, name) VALUES (26, 'Общая врачебная практика (семейная медицина)');
