CREATE TABLE `main` (
  `ID` bigint(20) unsigned NOT NULL default '0',
  `DateTime` datetime NOT NULL default '0000-00-00 00:00:00',
  `Title` varchar(50) NOT NULL default '',
  `EmployerType` tinyint(1) NOT NULL default '0',
  `Employer` varchar(100) default NULL,
  `City` varchar(50) default NULL,
  `Sex` tinyint(1) default NULL,
  `AgeFrom` tinyint(3) unsigned default NULL,
  `AgeTo` tinyint(3) unsigned default NULL,
  `Education` tinyint(3) unsigned default NULL,
  `Experience` tinyint(3) unsigned default NULL,
  `Employment` tinyint(3) unsigned default NULL,
  `Salary` int(10) unsigned default NULL,
  `Requirements` varchar(800) default NULL,
  `Duty` varchar(800) default NULL,
  `Conditions` varchar(400) default NULL,
  `Contact` varchar(50) NOT NULL default '',
  `Phone` varchar(50) NOT NULL default '',
  `Email` varchar(50) default NULL,
  `New` tinyint(1) NOT NULL default '1',
  `Priority` tinyint(3) NOT NULL default '0',
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=koi8r; 
