# Generated by Django 3.2.7 on 2021-10-03 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='Наименование')),
                ('date0', models.DateField(db_index=True, verbose_name='Дата начала')),
                ('date1', models.DateField(db_index=True, verbose_name='Дата окончания')),
                ('comments', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'ordering': ('date0', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('mult', models.BooleanField(db_index=True, help_text='&#9744;=radio, &#9745;=checkboxes', verbose_name='Multichoice')),
                ('payload', models.TextField(blank=True, help_text='Empty: text answer, multiline text: radio/checkboxes (1 line == 1 item)', null=True, verbose_name='Варианты')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ('poll', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.PositiveIntegerField(db_index=True, verbose_name='Пользователь')),
                ('resume', models.CharField(max_length=255, verbose_name='Ответ')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.quest', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ('cust_id', 'quest'),
                'unique_together': {('cust_id', 'quest')},
            },
        ),
    ]
