DEST=catmd
CPP=g++

CFLAGS =  -Wall `glib-config --cflags`
LDFLAGS = -lz `libole2-config --libs` `glib-config --libs`

.SUFFIXES: .c .cpp
.cpp.o:
	$(CPP) -c $(CFLAGS) $<

OBJS = \
	cc.o \
	commands.o \
	dialog.o \
	dump_data.o \
	expand.o \
	gallery.o \
	guiddata.o \
	main.o \
	menu.o \
	mdole_l.o \
	mms.o \
	mxl.o \
	mxl_in.o \
	mxl_out.o \
	panel.o \
	pic.o \
	prn_data.o \
	rights.o \
	storage.o \
	tree.o \
	ts.o

$(DEST): $(OBJS)
	$(CPP) -o $(DEST) $(LDFLAGS) $(OBJS)

clean:
	-rm -f *.o *~ $(DEST)
