CREATE TABLE main
	(
	ID		BIGINT	UNSIGNED	NOT NULL	PRIMARY KEY,
	DateTime	DATETIME		NOT NULL,
	Title		VARCHAR(400)		NOT NULL,
	EmployerType	BOOL			NOT NULL,
	Employer	VARCHAR(200)		NULL,
	City		VARCHAR(100)		NULL,
	Sex		BOOL			NULL,
	AgeFrom		TINYINT	UNSIGNED	NULL,
	AgeTo		TINYINT	UNSIGNED	NULL,
	Education	TINYINT	UNSIGNED	NULL,
	Experience	TINYINT	UNSIGNED	NULL,
	Employment	TINYINT	UNSIGNED	NULL,
	Salary		INT	UNSIGNED	NULL,
	Requirements	VARCHAR(1600)		NULL,
	Duty		VARCHAR(1600)		NULL,
	Conditions	VARCHAR(800)		NULL,
	Contact		VARCHAR(50)		NOT NULL,
	Phone		VARCHAR(50)		NOT NULL,
	Email		VARCHAR(50)		NULL,
	New		BOOL			NOT NULL	DEFAULT 1,
	Priority	TINYINT		NOT NULL	DEFAULT 0
	)
;
