BEGIN;
SELECT 'SRC:';
SELECT 'Src.Org', COUNT() FROM sro_org;
SELECT 'Src.Bld.StageLists', COUNT() FROM sro_permit;
SELECT 'Src.Bld.StageLists.Stages', COUNT() FROM sro_permitstage;
SELECT 'Src.Bld.StageLists.Stages.Jobs', COUNT() FROM sro_permitstagejob;
SELECT 'Src.Bld.Proto', COUNT() FROM sro_meeting;
SELECT 'Src.Prj.Orgs', COUNT() FROM sro_prjorg;
SELECT 'Src.Prj.StageLists', COUNT() FROM (SELECT DISTINCT org_id FROM sro_prjorgstage);
SELECT 'Src.Prj.StageLists.Stages', COUNT() FROM sro_prjorgstage;
SELECT 'Src.Prj.Proto', COUNT() FROM sro_prjproto;
SELECT 'DST:';
SELECT 'Dst.Orgs', COUNT() FROM sro2_org;
SELECT 'Dst.StageLists', COUNT() FROM sro2_stagelist;
SELECT 'Dst.Bld.Orgs', COUNT() FROM sro2_orgsro WHERE (sro_id=1);
SELECT 'Dst.Bld.Proto', COUNT() FROM sro2_protocol WHERE (sro_id=1);
SELECT 'Dst.Prj.Orgs', COUNT() FROM sro2_orgsro WHERE (sro_id=2);
SELECT 'Dst.Prj.Proto', COUNT() FROM sro2_protocol WHERE (sro_id=2);
SELECT 'Dst.StageLists', MAX(id) FROM sro2_stagelist;
SELECT 'Dst.StageLists.Stage', MAX(stagelist_id) FROM sro2_permitstage;
COMMIT;
