INSERT INTO employee_specialty (id, name, department_id) VALUES (1, 'Аллерголог', 2);
INSERT INTO employee_specialty (id, name, department_id) VALUES (2, 'Ассистент Стоматолога', 1);
INSERT INTO employee_specialty (id, name, department_id) VALUES (3, 'Врач УЗИ', 4);
INSERT INTO employee_specialty (id, name, department_id) VALUES (4, 'Врач-косметолог', 3);
INSERT INTO employee_specialty (id, name, department_id) VALUES (5, 'Гастроэнтеролог', 4);
INSERT INTO employee_specialty (id, name, department_id) VALUES (6, 'Дерматолог', 4);
INSERT INTO employee_specialty (id, name, department_id) VALUES (7, 'Детский массаж', 2);
INSERT INTO employee_specialty (id, name, department_id) VALUES (8, 'Кардиолог', 4);
INSERT INTO employee_specialty (id, name, department_id) VALUES (9, 'ЛОР', 2);
INSERT INTO employee_specialty (id, name, department_id) VALUES (10, 'Маникюр-педикюр', 3);
INSERT INTO employee_specialty (id, name, department_id) VALUES (11, 'Мануальный терапевт', 4);
INSERT INTO employee_specialty (id, name, department_id) VALUES (12, 'Массажист', 3);
INSERT INTO employee_specialty (id, name, department_id) VALUES (13, 'Медицинская сестра', 3);
INSERT INTO employee_specialty (id, name, department_id) VALUES (14, 'Невролог', 4);
INSERT INTO employee_specialty (id, name, department_id) VALUES (15, 'Невролог (дет.)', 2);
INSERT INTO employee_specialty (id, name, department_id) VALUES (16, 'Педиатр', 2);
INSERT INTO employee_specialty (id, name, department_id) VALUES (17, 'Процедурная медсестра', 1);
INSERT INTO employee_specialty (id, name, department_id) VALUES (18, 'Психотерапевт', 4);
INSERT INTO employee_specialty (id, name, department_id) VALUES (19, 'Рефлексотерапевт', 4);
INSERT INTO employee_specialty (id, name, department_id) VALUES (20, 'Стоматолог-Гигиенист', 1);
INSERT INTO employee_specialty (id, name, department_id) VALUES (21, 'Стоматолог-Ортодонт', 1);
INSERT INTO employee_specialty (id, name, department_id) VALUES (22, 'Стоматолог-Ортопед', 1);
INSERT INTO employee_specialty (id, name, department_id) VALUES (23, 'Стоматолог-Терапевт', 1);
INSERT INTO employee_specialty (id, name, department_id) VALUES (24, 'Стоматолог-Хирург', 1);
INSERT INTO employee_specialty (id, name, department_id) VALUES (25, 'Терапевт', 4);
INSERT INTO employee_specialty (id, name, department_id) VALUES (26, 'Травматолог-ортопед', 2);
INSERT INTO employee_specialty (id, name, department_id) VALUES (27, 'Физиотерапевт', 4);
INSERT INTO employee_specialty (id, name, department_id) VALUES (28, 'Эндокринолог', 4);
