BEGIN;
DELETE FROM sro2_insurer;
DELETE FROM sro2_okato;
DELETE FROM sro2_okopf;
DELETE FROM sro2_okved;
DELETE FROM sro2_srotype;
DELETE FROM sro2_sro;
DELETE FROM sro2_stage;
DELETE FROM sro2_job;
DELETE FROM sro2_speciality;
DELETE FROM sro2_specialitystage;
DELETE FROM sro2_skill;
DELETE FROM sro2_eventtype;
DELETE FROM sro2_role;
DELETE FROM sro2_person;
DELETE FROM sro2_personskill;
DELETE FROM sro2_org;
DELETE FROM sro2_orgokved;
DELETE FROM sro2_orgphone;
DELETE FROM sro2_orgemail;
DELETE FROM sro2_orgwww;
DELETE FROM sro2_orgstuff;
DELETE FROM sro2_orgsro;
DELETE FROM sro2_orgevent;
DELETE FROM sro2_orglicense;
DELETE FROM sro2_orginsurance;
DELETE FROM sro2_stagelisttype;
DELETE FROM sro2_stagelist;
DELETE FROM sro2_permitstage;
DELETE FROM sro2_permitstagejob;
DELETE FROM sro2_protocol;
DELETE FROM sro2_statement;
DELETE FROM sro2_permit;
INSERT INTO sro2_insurer (id, name, fullname) SELECT id, name, fullname FROM sro_insurer;
INSERT INTO sro2_okato (id, name) SELECT id, name FROM sro_okato;
INSERT INTO sro2_okopf (id, name, shortname, namedp, disabled, parent_id) SELECT id, name, shortname, namedp, disabled, parent_id FROM sro_okopf;
INSERT INTO sro2_okved (id, name, parent_id) SELECT id, name, parent_id FROM sro_okved;
INSERT INTO sro2_srotype (id, name) VALUES (1, 'Строительство');
INSERT INTO sro2_srotype (id, name) VALUES (2, 'Проектирование');
INSERT INTO sro2_sro (id, name, fullname, regno, type_id, own, boss, ftp, path) VALUES (1, 'МООЖС', '"Межрегиональное объединение организаций железнодорожного строительства"', 'СРО-С-043-28092009', 1, 1, 'Г. Н. Талашкин', 'ftp.moozs.ru', 'moozs.ru/docs/joom/images');
INSERT INTO sro2_sro (id, name, fullname, regno, type_id, own, boss, ftp, path) VALUES (2, 'МООАСП', '"Межрегиональное объединение организаций архитектурно-строительного проектирования"', 'СРО-П-115-18012010', 2, 1, 'В. А. Сасалин', 'ftp.moozs.ru', 'mooasp.ru/docs/joom/images/stories/docs');
-- INSERT INTO sro2_sro (id, name, fullname, regno, type_id, own) SELECT id+2, name, fullname, regno, 1, 0 FROM sro_sro;
INSERT INTO sro2_stage (id, srotype_id, no, name, hq, hs, mq, ms) SELECT id, 1, id, name, hq, hs, mq, ms FROM sro_stage;
INSERT INTO sro2_stage (id, srotype_id, no, name, hq, hs, mq, ms) SELECT 100+id, 2, id, name, hq, hs, mq, ms FROM sro_prjstage;
INSERT INTO sro2_job (id, stage_id, okdp, name) SELECT id, stage_id, okdp, name FROM sro_job;
INSERT INTO sro2_speciality (id, name) SELECT id, name FROM sro_speciality;
INSERT INTO sro2_specialitystage (id, speciality_id, stage_id) SELECT id, speciality_id, stage_id FROM sro_specialitystage;
INSERT INTO sro2_skill (id, name, high) SELECT id, name, high FROM sro_skill;
INSERT INTO sro2_eventtype (id, name, comments) SELECT id, name, comments FROM sro_eventtype;
INSERT INTO sro2_role (id, name, comments) SELECT id, name, comments FROM sro_role;
INSERT INTO sro2_person (id, firstname, midname, lastname, phone) SELECT id, firstname, midname, lastname, phone FROM sro_person;
INSERT INTO sro2_personskill (person_id, speciality_id, skill_id, year, skilldate, school, seniority, seniodate, tested, courseno, coursedate, coursename, courseschool) SELECT person_id, speciality_id, skill_id, year, skilldate, school, seniority, seniodate, tested, courseno, coursedate, coursename, courseschool FROM sro_personskill;
INSERT INTO sro2_org (id, name, fullname, okopf_id, egruldate, inn, kpp, ogrn, okato_id, laddress, raddress, comments) SELECT id, name, fullname, okopf_id, egruldate, inn, kpp, ogrn, okato_id, laddress, raddress, comments FROM sro_org;
INSERT INTO sro2_orgokved (org_id, okved_id) SELECT org_id, okved_id FROM sro_orgokved;
INSERT INTO sro2_orgphone (org_id, phone) SELECT org_id, phone FROM sro_orgphone;
INSERT INTO sro2_orgemail (org_id, URL) SELECT org_id, URL FROM sro_orgemail;
INSERT INTO sro2_orgwww (org_id, URL) SELECT org_id, URL FROM sro_orgwww;
INSERT INTO sro2_orgstuff (org_id, role_id, person_id, leader, permanent) SELECT org_id, role_id, person_id, leader, permanent FROM sro_orgstuff;
INSERT INTO sro2_stagelisttype (id, name)  VALUES (1, 'Заявление');
INSERT INTO sro2_stagelisttype (id, name)  VALUES (2, 'Свидетельство');
-- 1. Building
INSERT INTO sro2_orgsro (id, org_id, sro_id, regno, regdate, paydate, paysum, paydatevv, comments, publish) SELECT id, id, 1, sroregno, sroregdate, paydate, paysum, paydatevv, comments, public FROM sro_org;
INSERT INTO sro2_orgevent (orgsro_id, type_id, date, comments) SELECT org_id, type_id, date, comments FROM sro_orgevent;
INSERT INTO sro2_orglicense (orgsro_id, no, datefrom, datedue) SELECT org_id, no, datefrom, datedue FROM sro_orglicense;
INSERT INTO sro2_orginsurance (orgsro_id, insurer_id, no, date, sum, datefrom, datedue) SELECT org_id, insurer_id, insno, insdate, insum, datefrom, datetill FROM sro_orginsurance;
INSERT INTO sro2_stagelist (id, orgsro_id, type_id) SELECT id, org_id, 3 - permittype_id FROM sro_permit WHERE permittype_id < 3;	/* statement & permit*/
INSERT INTO sro2_permitstage (id, stagelist_id, stage_id) SELECT id, permit_id, stage_id FROM sro_permitstage;
INSERT INTO sro2_permitstagejob (permitstage_id, job_id) SELECT permitstage_id, job_id FROM sro_permitstagejob;
INSERT INTO sro2_statement (stagelist_id, date) SELECT permit_id, date FROM sro_permitstatement;
INSERT INTO sro2_protocol (id, sro_id, no, date) SELECT id, 1, regno, date FROM sro_meeting;
INSERT INTO sro2_permit (stagelist_id, no, date, datedue, protocol_id) SELECT sro_permitown.permit_id, sro_org.sroregno || '-' || sro_permitown.regno, sro_permitown.date, sro_permitown.datedue, sro_permitown.meeting_id FROM sro_permitown JOIN sro_permit ON sro_permitown.permit_id=sro_permit.id JOIN sro_org ON sro_org.id=sro_permit.org_id;
-- 2. Projecting
INSERT INTO sro2_orgsro (id, org_id, sro_id, regno, regdate, paydate, paysum, paydatevv, comments, publish) SELECT id + (SELECT MAX(id) FROM sro_org), org_id, 2, regno, regdate, paydate, paysum, paydatevv, comments, publish FROM sro_prjorg;
INSERT INTO sro2_orglicense (orgsro_id, no, datefrom, datedue) SELECT id + (SELECT MAX(id) FROM sro_org), licno, licfrom, licdue FROM sro_prjorg WHERE (licfrom NOT NULL) AND (licdue NOT NULL);
INSERT INTO sro2_orginsurance (orgsro_id, insurer_id, no, date, sum, datefrom, datedue) SELECT id + (SELECT MAX(id) FROM sro_org), insurer_id, insno, insdate, inssum, insfrom, insdue FROM sro_prjorg WHERE insurer_id NOT NULL AND insno NOT NULL AND insdate NOT NULL AND inssum NOT NULL;
INSERT INTO sro2_stagelist (id, orgsro_id, type_id) SELECT id + (SELECT MAX(id) FROM sro_permit), id + (SELECT MAX(id) FROM sro_org), 2 FROM sro_prjorg WHERE permno NOT NULL;
INSERT INTO sro2_permitstage (stagelist_id, stage_id) SELECT id + (SELECT MAX(id) FROM sro_permit), 100+stage_id FROM sro_prjorgstage;
INSERT INTO sro2_protocol (id, sro_id, no, date) SELECT id + (SELECT MAX(id) FROM sro_meeting), 2, no, date FROM sro_prjproto;
INSERT INTO sro2_permit (stagelist_id, no, date, protocol_id) SELECT id + (SELECT MAX(id) FROM sro_permit), permno, permdate, protocol_id + (SELECT MAX(id) FROM sro_meeting) from sro_prjorg;
COMMIT;
