#!/bin/sh
# Delete all tables
. ./VARS
TMP=`mktemp`
echo "BEGIN;" > $TMP
echo "SHOW TABLES;" | $MGR dbshell | grep ^$APP | while read i; do echo "DROP TABLE $i;" >> $TMP; done
echo "COMMIT;" >> $TMP
cat $TMP | $MGR dbshell
rm -f $TMP
